# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/test_nbdev/00 define in sub.ipynb (unless otherwise specified).

__all__ = ['defined_in_subfolder']

# Cell
def defined_in_subfolder():
    print("This function was defined in a subfolder")