# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/test_nbdev/02 define in multiple nbs 2.ipynb (unless otherwise specified).

__all__ = ['defined_in_multiple_nbs', 'defined_in_multiple_nbs']

# Cell

def defined_in_multiple_nbs():
    print("This function was defined on notebook 01")

# Cell

def defined_in_multiple_nbs():
    print("This function was defined on notebook 02")